# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d2513e84eb605b6571597d322ac97642cab2d0183db6921f621ebfe122308bd48af7a4a0c6c7d9018868730cbe378d3f10c20959b5bc0303b1ed0428775966b

test:
  secret_key_base: 5e8af0ba490e597f26318b8d545feebf01a6dee560a0cad7def8e0aadb18c6458c88ec84b79d03a99683252c75860825d5b3696f7ea0d05267c55a6881fde387

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
